# In general, this file (when sourced from https://github.com/chainguard-dev/pre-commit-hooks)
# should be able to be used as-is in other repos such as wolfi-dev/os, enterprise-packages, and extra-packages,
# and can be assumed to be the "source of truth" for our pre-commit rules.
# See https://eng.inky.wtf/docs/technical/git/pre-commit for info on how to edit this file.
repos:
  - repo: https://github.com/chainguard-dev/pre-commit-hooks
    rev: e4d1134a14c8decd027fb46f6a46b42f79d3fb23
    hooks:
      - id: shellcheck-run-steps
        files: '^[^.][^/]*\.yaml$' # matches non-hidden .yaml files at the top level only
        exclude: '^celeborn-0\.5\.yaml$' # for details see https://github.com/chainguard-dev/internal-dev/issues/18336
        args:
          - "--" # options to hook before this, options to shellcheck after
          - "-S"
          - "error"
          - "--" # terminates shellcheck options, rest will be filenames
      - id: check-for-epoch-bump
        files: |
          (?x)^(
              [^/]+\.ya?ml                      # matches .yaml or .yml files at the top level only
          )$
  - repo: https://github.com/chainguard-dev/yam
    rev: 768695300c5f663012a77911eb4920c12e5ed2e5 # frozen: v0.2.26
    hooks:
      - id: yam
        files: |
          (?x)^(
              [^/]+\.ya?ml |                    # matches .yaml or .yml files at the top level only
              [^/]+/pombump[^/]*\.ya?ml |       # pombump*.yaml exactly 1 dir deep
              [^/]+/cargobump[^/]*\.ya?ml |     # cargobump*.yaml exactly 1 dir deep
              pipelines/.* |                    # anything under pipelines/
              \.github/.*                       # anything under .github/
          )$
        exclude: |
          (?x)^(
              .*\.patch |
              .*\.diff
          )$
  - repo: https://github.com/wolfi-dev/wolfictl
    rev: ddadb9365d6d78ee33e13801b12eabfcb04298a7 # 2025-06-20
    hooks:
      - id: wolfictl-lint
  - repo: https://github.com/golangci/misspell
    rev: e78f9b6cd537559a24525b6ea7e182794edfd31f # frozen: v0.7.0
    hooks:
      - id: misspell
        # To add exclusions, add (misspelled) words to the -i arg, comma separated, or
        # add files to the exclude array (with trailing | unless last it's the last one).
        # Syntax info: https://pre-commit.com/#regular-expressions
        # Dictionary of corrections: https://github.com/golangci/misspell/blob/main/words.go
        args:
          - "-i=routeros,mosquitto,metagem,rela,exportfs"
        files: |
          (?x)^(
              [^/]+\.ya?ml |                    # matches .yaml or .yml files at the top level only
              [^/]+/pombump[^/]*\.ya?ml |       # pombump*.yaml exactly 1 dir deep
              [^/]+/cargobump[^/]*\.ya?ml |     # cargobump*.yaml exactly 1 dir deep
              pipelines/.* |                    # anything under pipelines/
              \.github/.*                       # anything under .github/
          )$
        exclude: |
          (?x)^(
              aws-network-policy-agent/pkg/ebpf/c/vmlinux.h-aarch64|
              aws-network-policy-agent/pkg/ebpf/c/vmlinux.h-x86_64|
              .*\.patch
          )$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      - id: check-yaml
        files: |
          (?x)^(
              [^/]+\.ya?ml |                    # matches .yaml or .yml files at the top level only
              [^/]+/pombump[^/]*\.ya?ml |       # pombump*.yaml exactly 1 dir deep
              [^/]+/cargobump[^/]*\.ya?ml |     # cargobump*.yaml exactly 1 dir deep
              pipelines/.* |                    # anything under pipelines/
              \.github/.*                       # anything under .github/
          )$
        exclude: |
          (?x)^(
              .*\.patch
          )$
      - id: forbid-submodules
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
        exclude: ^(ruby-3\.0/0001-ruby-3\.0\.6-openssl-patch\.patch|gitleaks\.yaml)$
