# In general, this file (when sourced from https://github.com/chainguard-dev/pre-commit-hooks)
# should be able to be used as-is in other repos such as wolfi-dev/os, enterprise-packages, and extra-packages,
# and can be assumed to be the "source of truth" for our pre-commit rules.
# See https://eng.inky.wtf/docs/technical/git/pre-commit for info on how to edit this file.
repos:
  - repo: https://github.com/chainguard-dev/pre-commit-hooks
    rev: 71fca50bcd1006b5cbcf71f03a3b493f48c4af7f
    hooks:
      #- id: shellcheck-run-steps # Not quite ready yet for prime time
      - id: check-for-epoch-bump
  - repo: https://github.com/chainguard-dev/yam
    rev: 693d578a25dccd5beb548984d7a3cbda40c3af41 # frozen: v0.2.16
    hooks:
      - id: yam
  - repo: https://github.com/wolfi-dev/wolfictl
    rev: ddadb9365d6d78ee33e13801b12eabfcb04298a7 # 2025-06-20
    hooks:
      - id: wolfictl-lint
  - repo: https://github.com/golangci/misspell
    rev: e78f9b6cd537559a24525b6ea7e182794edfd31f # frozen: v0.7.0
    hooks:
      - id: misspell
        # To add exclusions, add (misspelled) words to the -i arg, comma separated, or
        # add files to the exclude array (with trailing | unless last it's the last one).
        # Syntax info: https://pre-commit.com/#regular-expressions
        # Dictionary of corrections: https://github.com/golangci/misspell/blob/main/words.go
        args:
          - "-i=routeros,mosquitto,metagem,rela,exportfs"
        exclude: |
          (?x)^(
              aws-network-policy-agent/pkg/ebpf/c/vmlinux.h-aarch64|
              aws-network-policy-agent/pkg/ebpf/c/vmlinux.h-x86_64|
              fontforge/gettext-0.22.patch|
              helix/GHSA-2frx-2596-x5r6-fix.patch
          )$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      - id: check-yaml
      - id: forbid-submodules
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
        exclude: ^ruby-3\.0/0001-ruby-3\.0\.6-openssl-patch\.patch$
