repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # Use commit hashes here, not tags.
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      - id: check-yaml
      - id: forbid-submodules
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
        exclude: ^ruby-3\.0/0001-ruby-3\.0\.6-openssl-patch\.patch$
