package:
  name: aws-application-networking-k8s
  version: "1.2.0"
  epoch: 1
  description: A Kubernetes controller for Amazon VPC Lattice
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - aws-gateway-controller=${{package.full-version}}

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0de30baee7a5e8292f8089d5faef060b4d2edc9d
      repository: https://github.com/aws/aws-application-networking-k8s
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/oauth2@v0.27.0

  - uses: go/build
    with:
      packages: ./cmd/aws-application-networking-k8s/main.go
      tidy: true
      output: manager

subpackages:
  - name: ${{package.name}}-compat
    description: "upstream image have executable placed at /"
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/
          ln -sf /usr/bin/manager ${{targets.contextdir}}/manager

update:
  enabled: true
  github:
    identifier: aws/aws-application-networking-k8s
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - name: helm message
      runs: |
        manager --help
    - name: log grep
      runs: |
        manager 2>&1 | grep "init config failed"
