package:
  name: aws-application-networking-k8s
  version: 1.0.7
  epoch: 0
  description: A Kubernetes controller for Amazon VPC Lattice
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - aws-gateway-controller=${{package.full-version}}

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 03fdeb6fc933de7fbe3a1c5e4ee1438fae022313
      repository: https://github.com/aws/aws-application-networking-k8s
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.23.0 google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      packages: ./cmd/aws-application-networking-k8s/main.go
      tidy: true
      output: manager

subpackages:
  - name: ${{package.name}}-compat
    description: "upstream image have executable placed at /"
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/
          ln -sf /usr/bin/manager ${{targets.contextdir}}/manager

update:
  enabled: true
  github:
    identifier: aws/aws-application-networking-k8s
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - name: helm message
      runs: manager -h
    - name: log grep
      runs: manager 2>&1 | grep "init config failed"
