package:
  name: aws-application-networking-k8s
  version: "2.0.0"
  epoch: 0 # CVE-2025-47910
  description: A Kubernetes controller for Amazon VPC Lattice
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - aws-gateway-controller=${{package.full-version}}

pipeline:
  - uses: git-checkout
    with:
      expected-commit: aa756dc0cc80372848019f10655eb5e9ef491936
      repository: https://github.com/aws/aws-application-networking-k8s
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/aws-application-networking-k8s/main.go
      tidy: true
      output: manager

subpackages:
  - name: ${{package.name}}-compat
    description: "upstream image have executable placed at /"
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/
          ln -sf /usr/bin/manager ${{targets.contextdir}}/manager
    # test added by a robot (compat)
    test:
      pipeline:
        - runs: |
            readlink -v /manager

update:
  enabled: true
  github:
    identifier: aws/aws-application-networking-k8s
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - name: helm message
      runs: |
        manager --help
    - name: log grep
      runs: |
        manager 2>&1 | grep "init config failed"
