package:
  name: cass-config-builder
  version: 1.0.8
  epoch: 0
  description: |
    Configuration builder for Apache Cassandra based on definitions at datastax/cass-config-definitions
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - openjdk-8-default-jvm

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - openjdk-8-default-jvm

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/datastax/cass-config-builder
      expected-commit: 03ba452b6af0258020cb0c79040a558dc03704b2
      tag: v${{package.version}}

  - uses: patch
    with:
      # to mitigate the CVEs related to the package
      patches: deps.patch

  - runs: |
      sed -i 's|git@\(.*\):|https://\1/|g' .gitmodules
      cat .gitmodules
      git submodule update --init

  - runs: |
      export JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
      ./gradlew copyDockerBuildCtx
      mkdir -p "${{targets.destdir}}"/usr/local/bin
      mkdir -p "${{targets.destdir}}"/definitions
      cp -r build/docker/bin/* "${{targets.destdir}}"/usr/local/bin
      cp -r build/docker/definitions/* "${{targets.destdir}}"/definitions
      cp -r build/docker/*.jar "${{targets.destdir}}"/usr/local/bin/

update:
  enabled: true
  github:
    identifier: datastax/cass-config-builder
    strip-prefix: v
    use-tag: true
