package:
  name: configmap-reload
  version: "0.15.0"
  epoch: 7
  description: Simple binary to trigger a reload when a Kubernetes ConfigMap is updated
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+)\.\d+\.\d+$
    replace: "$1"
    to: major-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jimmidyson/configmap-reload
      expected-commit: 3f1e9babda3b94b235d203712c17cb88c53d43d8
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: configmap-reload.go
      output: configmap-reload
      ldflags: -extldflags '-static'

subpackages:
  - name: ${{package.name}}-iamguarded-compat
    options:
      no-provides: true
    pipeline:
      - uses: iamguarded/build-compat
        with:
          package: configmap-reload
          version: ${{vars.major-version}}
      - runs: |
          mkdir -p "/opt/iamguarded/configmap-reload/bin/"
          ln -s "/usr/bin/configmap-reload" "/opt/iamguarded/configmap-reload/bin/configmap-reload"
      - uses: iamguarded/finalize-compat
        with:
          package: configmap-reload
          version: ${{vars.major-version}}
    test:
      pipeline:
        - uses: iamguarded/test-compat
          with:
            package: configmap-reload
            version: ${{vars.major-version}}

update:
  enabled: true
  github:
    identifier: jimmidyson/configmap-reload
    strip-prefix: v
    tag-filter: v
    use-tag: true

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        configmap-reload --help
