package:
  name: configurable-http-proxy
  version: "5.1.1"
  epoch: 0 # go/wolfi-rsc/configurable-http-proxy
  description: "HTTP parser written against llparse"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - nodejs-18
  resources:
    cpu: "1"
    memory: 2Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - nodejs-18
      - npm
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: fc4704dc3d3723fd04e4a6d30891a19d121d33da
      repository: https://github.com/jupyterhub/configurable-http-proxy
      tag: ${{package.version}}

  - runs: |
      mkdir -p ${{targets.destdir}}/srv/${{package.name}}
      cp chp-docker-entrypoint package.json index.js ${{targets.destdir}}/srv/${{package.name}}/
      cp -r bin/ doc/ lib/ test/ ${{targets.destdir}}/srv/${{package.name}}/

  - working-directory: ${{targets.destdir}}/srv/${{package.name}}
    pipeline:
      - runs: |
          npm install --package-lock-only
          npm ci --production
      - uses: strip

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      ln -sf /srv/${{package.name}}/bin/${{package.name}} ${{targets.destdir}}/usr/bin/${{package.name}}

update:
  enabled: true
  github:
    identifier: jupyterhub/configurable-http-proxy
    use-tag: true

test:
  pipeline:
    - runs: |
        configurable-http-proxy --version
        configurable-http-proxy --help
