package:
  name: configurable-http-proxy
  version: 4.6.1
  epoch: 1
  description: "HTTP parser written against llparse"
  copyright:
    - license: BSD 3-Clause
  dependencies:
    runtime:
      - nodejs-18

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - nodejs-18
      - npm
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: d3af2e9e2a5b7385fc93bcfe2b81470e4a867daf
      repository: https://github.com/jupyterhub/configurable-http-proxy
      tag: ${{package.version}}

  - runs: |
      mkdir -p ${{targets.destdir}}/srv/${{package.name}}
      cp chp-docker-entrypoint package.json index.js ${{targets.destdir}}/srv/${{package.name}}/
      cp -r bin/ doc/ lib/ test/ ${{targets.destdir}}/srv/${{package.name}}/

  - working-directory: ${{targets.destdir}}/srv/${{package.name}}
    pipeline:
      - runs: |
          npm install --package-lock-only
          npm ci --production
      - uses: strip

update:
  enabled: true
  github:
    identifier: jupyterhub/configurable-http-proxy
    use-tag: true
