package:
  name: fontconfig
  version: 2.14.2
  epoch: 1
  description: Library for configuring and customizing font access
  copyright:
    - license: MIT
  scriptlets:
    trigger:
      paths:
        - /usr/share/fonts/*
      script: |
        #!/bin/sh
        fc-cache --system-only > /dev/null
environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - freetype-dev
      - expat-dev
      - python3-dev
      - gperf
      - zlib-dev
      - brotli-dev
      - libpng-dev
      - bzip2-dev
      # - docbook2x # TODO disabling docs so we can avoid docbook2x for now
pipeline:
  - uses: fetch
    with:
      expected-sha256: 3ba2dd92158718acec5caaf1a716043b5aa055c27b081d914af3ccb40dce8a55
      uri: https://www.freedesktop.org/software/fontconfig/release/fontconfig-${{package.version}}.tar.gz
  - runs: rm -f src/fcobjshash.h
  - uses: autoconf/configure
    with:
      opts: |
        --enable-static \
        --enable-docs \
        --disable-nls \
        --disable-docs
  # --disable-docs to avoid building docbook* packages for now
  - runs: rm -f src/fcobjhash.h
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
subpackages:
  - name: fontconfig-static
    description: fontconfig static library
    pipeline:
      - uses: split/static
  - name: fontconfig-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - fontconfig
    description: fontconfig dev
update:
  enabled: true
  release-monitor:
    identifier: 827
