package:
  name: fontconfig
  version: 2.14.0
  epcho: 0
  description: Library for configuring and customizing font access
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: MIT
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - freetype-dev
      - expat-dev
      - python3-dev
      - python3
      - gperf
      - zlib-dev
      - brotli-dev
      - libpng-dev
      - bzip2-dev
      # - docbook2x # TODO disabling docs so we can avoid docbook2x for now
pipeline:
  - uses: fetch
    with:
      expected-sha256: b8f607d556e8257da2f3616b4d704be30fd73bd71e367355ca78963f9a7f0434
      uri: https://www.freedesktop.org/software/fontconfig/release/fontconfig-${{package.version}}.tar.gz
  - runs: rm -f src/fcobjshash.h
  - uses: autoconf/configure
    with:
      opts: |
        --enable-static \
        --enable-docs \
        --disable-nls \
        --disable-docs
  # --disable-docs to avoid building docbook* packages for now
  - runs: rm -f src/fcobjhash.h
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip

subpackages:
  - name: fontconfig-static
    description: fontconfig static library
    pipeline:
      - uses: split/static
  - name: fontconfig-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - fontconfig
    description: fontconfig dev
