package:
  name: fontconfig
  version: 2.15.0
  epoch: 0
  description: Library for configuring and customizing font access
  copyright:
    - license: MIT
  scriptlets:
    trigger:
      paths:
        - /usr/share/fonts/*
      script: |
        #!/bin/sh
        fc-cache --system-only > /dev/null

environment:
  contents:
    packages:
      - autoconf
      - automake
      - brotli-dev
      - build-base
      - busybox
      - bzip2-dev
      # - docbook2x # TODO disabling docs so we can avoid docbook2x for now
      - ca-certificates-bundle
      - expat-dev
      - freetype-dev
      - gperf
      - libpng-dev
      - python3-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: f5f359d6332861bd497570848fcb42520964a9e83d5e3abe397b6b6db9bcaaf4
      uri: https://www.freedesktop.org/software/fontconfig/release/fontconfig-${{package.version}}.tar.gz

  - runs: rm -f src/fcobjshash.h

  - uses: autoconf/configure
    with:
      opts: |
        --enable-static \
        --enable-docs \
        --disable-nls \
        --disable-docs

  # --disable-docs to avoid building docbook* packages for now
  - runs: rm -f src/fcobjhash.h

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: fontconfig-static
    description: fontconfig static library
    pipeline:
      - uses: split/static

  - name: fontconfig-config
    description: fontconfig configuration data
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr
          mv "${{targets.destdir}}"/usr/share "${{targets.subpkgdir}}"/usr/
          mv "${{targets.destdir}}"/etc "${{targets.subpkgdir}}"/etc

  - name: libfontconfig1
    description: fontconfig shared library
    dependencies:
      runtime:
        - fontconfig-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libfontconfig.so.* "${{targets.subpkgdir}}"/usr/lib

  - name: fontconfig-dev
    pipeline:
      - uses: split/dev
    description: fontconfig dev

update:
  enabled: true
  release-monitor:
    identifier: 827
