package:
  name: fontconfig
  version: "2.16.2"
  epoch: 0
  description: Library for configuring and customizing font access
  copyright:
    - license: MIT
  scriptlets:
    trigger:
      paths:
        - /usr/share/fonts/*
      script: |
        #!/bin/sh
        fc-cache --system-only > /dev/null

environment:
  contents:
    packages:
      - autoconf
      - automake
      - brotli-dev
      - build-base
      - busybox
      - bzip2-dev
      # - docbook2x # TODO disabling docs so we can avoid docbook2x for now
      - ca-certificates-bundle
      - expat-dev
      - freetype-dev
      - gettext-dev
      - gperf
      - libpng-dev
      - libtool
      - python3-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.freedesktop.org/fontconfig/fontconfig.git
      tag: ${{package.version}}
      expected-commit: c1bdf4f542f56d3b5035ec2806ed7a685f831c1b

  - runs: |
      rm -f src/fcobjshash.h
      ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: |
        --enable-static \
        --enable-docs \
        --disable-nls \
        --disable-docs

  # --disable-docs to avoid building docbook* packages for now
  - runs: rm -f src/fcobjhash.h

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: fontconfig-static
    description: fontconfig static library
    pipeline:
      - uses: split/static

  - name: fontconfig-config
    description: fontconfig configuration data
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr
          mv "${{targets.destdir}}"/usr/share "${{targets.subpkgdir}}"/usr/
          mv "${{targets.destdir}}"/etc "${{targets.subpkgdir}}"/etc

  - name: libfontconfig1
    description: fontconfig shared library
    dependencies:
      runtime:
        - fontconfig-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libfontconfig.so.* "${{targets.subpkgdir}}"/usr/lib
    test:
      pipeline:
        - uses: test/tw/ldd-check

  - name: fontconfig-dev
    pipeline:
      - uses: split/dev
    description: fontconfig dev
    test:
      pipeline:
        - uses: test/pkgconf
        - uses: test/tw/ldd-check

update:
  enabled: true
  release-monitor:
    identifier: 827

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        fc-cache --version
        fc-cat --version
        fc-conflist --version
        fc-list --version
        fc-match --version
        fc-pattern --version
        fc-query --version
        fc-scan --version
        fc-validate --version
        fc-cache --help
        fc-cat --help
        fc-conflist --help
        fc-list --help
        fc-match --help
        fc-pattern --help
        fc-query --help
        fc-scan --help
        fc-validate --help
