package:
  name: haproxy-ingress
  version: 0.14.7
  epoch: 5
  description: HAProxy Ingress
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - busybox
      - dumb-init
      - haproxy
      - lua-json4

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jcmoraisjr/haproxy-ingress
      tag: v${{package.version}}
      expected-commit: aa2c1bd0723ba9e134701685d4ee42b5e8c5a083

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0
      tidy: false # changes to the dependencies broke this service after bumping crypto. https://github.com/chainguard-dev/image-release-stats/issues/3326

  - runs: |
      make GOOS=$(go env GOOS) GOARCH=$(go env GOARCH) linux-build
      mkdir -p ${{targets.destdir}}/usr/bin
      mkdir -p ${{targets.destdir}}/haproxy-ingress

      # Copy the /etc directory to the new rootfs
      mv ./rootfs/etc ${{targets.destdir}}

      # Move the startup scripts to /usr/bin
      mv ./rootfs/*.sh ${{targets.destdir}}/usr/bin/

      mkdir -p ${{targets.destdir}}/var/empty  ${{targets.destdir}}/etc/lua ${{targets.destdir}}/etc/haproxy ${{targets.destdir}}/var/lib/haproxy
      install -Dm755 ./rootfs/haproxy-ingress-controller ${{targets.destdir}}/usr/bin/haproxy-ingress-controller

  - uses: strip

subpackages:
  - name: "haproxy-ingress-compat"
    description: "Compatibility package to place binaries in the location expected by upstream start.sh script"
    pipeline:
      - runs: |
          # The helm chart expects the haproxy-ingress-compat binaries to be in / instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/haproxy-ingress-controller ${{targets.subpkgdir}}/haproxy-ingress-controller

          for script in start.sh haproxy-shutdown.sh haproxy-reload.sh; do
            ln -sf /usr/bin/$script ${{targets.subpkgdir}}/$script
          done
      - uses: strip

update:
  enabled: true
  github:
    identifier: jcmoraisjr/haproxy-ingress
    strip-prefix: v
    use-tag: true
    tag-filter: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        haproxy-ingress-controller --version
