package:
  name: haproxy-ingress
  version: 0.14.2
  epoch: 1
  description: HAProxy Ingress
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - busybox
      - dumb-init
      - haproxy
      - lua-json4

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - build-base
      - go
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jcmoraisjr/haproxy-ingress
      tag: v${{package.version}}
      expected-commit: 559188a803c67c7e8cbeaaecef11cdee3e064ff6

  - runs: |
      # Mitigate GHSA-r48q-9g5r-8q2h
      go get github.com/emicklei/go-restful@v2.16.0

      # Mitigate GHSA-vvpx-j8f3-3w6h
      go get golang.org/x/net@v0.7.0

      go mod tidy

  - runs: |
      make GOOS=$(go env GOOS) GOARCH=$(go env GOARCH) linux-build
      mkdir -p ${{targets.destdir}}/usr/bin
      mkdir -p ${{targets.destdir}}/haproxy-ingress

      # Copy the /etc directory to the new rootfs
      mv ./rootfs/etc ${{targets.destdir}}

      # Move the startup scripts to /usr/bin
      mv ./rootfs/*.sh ${{targets.destdir}}/usr/bin/

      mkdir -p ${{targets.destdir}}/var/empty  ${{targets.destdir}}/etc/lua ${{targets.destdir}}/etc/haproxy ${{targets.destdir}}/var/lib/haproxy ${{targets.destdir}}/var/run/haproxy
      install -Dm755 ./rootfs/haproxy-ingress-controller ${{targets.destdir}}/usr/bin/haproxy-ingress-controller

  - uses: strip

subpackages:
  - name: "haproxy-ingress-compat"
    description: "Compatibility package to place binaries in the location expected by upstream start.sh script"
    pipeline:
      - runs: |
          # The helm chart expects the kiam binaries to be in / instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/haproxy-ingress-controller ${{targets.subpkgdir}}/haproxy-ingress-controller

          for script in start.sh haproxy-shutdown.sh haproxy-reload.sh; do
            ln -sf /usr/bin/$script ${{targets.subpkgdir}}/$script
          done
      - uses: strip

update:
  enabled: true
  github:
    identifier: jcmoraisjr/haproxy-ingress
    strip-prefix: v
    use-tag: true
    tag-filter: v
