package:
  name: ingress-nginx-controller
  version: 1.8.0
  epoch: 0
  description: "Ingress-NGINX Controller for Kubernetes"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - go
      - bash
      - curl
      - git
      - openssh-client
      - libcap

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes/ingress-nginx
      tag: controller-v${{package.version}}
      expected-commit: 3476232f5c38383dd157ddaff3b4c7cebd57284e

  - name: Build ingress-nginx controller from source
    runs: |
      set -o errexit
      set -o nounset
      set -o pipefail

      export PKG="k8s.io/ingress-nginx"
      export COMMIT_SHA=$(git rev-parse --short HEAD)
      export REPO_INFO=$(git config --get remote.origin.url)$

      mkdir -p ${{targets.destdir}}

      export CGO_ENABLED=0

      go build -v \
      -trimpath -ldflags="-buildid= -w -s \
      -X ${PKG}/version.RELEASE=controller-v${{package.version}} \
      -X ${PKG}/version.COMMIT=${COMMIT_SHA} \
      -X ${PKG}/version.REPO=${REPO_INFO}" \
      -o "${{targets.destdir}}/dbg" ${PKG}/cmd/dbg

      go build -v \
      -trimpath -ldflags="-buildid= -w -s \
      -X ${PKG}/version.RELEASE=controller-v${{package.version}} \
      -X ${PKG}/version.COMMIT=${COMMIT_SHA} \
      -X ${PKG}/version.REPO=${REPO_INFO}" \
      -o "${{targets.destdir}}/waitshutdown" ${PKG}/cmd/waitshutdown

      go build -v \
      -trimpath -ldflags="-buildid= -w -s \
      -X ${PKG}/version.RELEASE=controller-v${{package.version}} \
      -X ${PKG}/version.COMMIT=${COMMIT_SHA} \
      -X ${PKG}/version.REPO=${REPO_INFO}" \
      -o "${{targets.destdir}}/nginx-ingress-controller" ${PKG}/cmd/nginx

      setcap cap_net_bind_service=+ep ${{targets.destdir}}/nginx-ingress-controller \
      && setcap -v cap_net_bind_service=+ep ${{targets.destdir}}/nginx-ingress-controller

update:
  enabled: true
  github:
    identifier: kubernetes/ingress-nginx
    strip-prefix: controller-v
    use-tag: true
    tag-filter: "controller-v*"
