package:
  name: kubernetes-ingress-defaultbackend
  version: "1.34.2"
  epoch: 0
  description: 'A simple web server that respond 404 common used in kubernetes ingress, serve pages 404 at root and 200 at /healthz'
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes/ingress-gce
      tag: v${{package.version}}
      expected-commit: 6359d68f7f0bc3f0729bd6b44b6bc82652c2b640

  - uses: go/build
    with:
      packages: ./cmd/404-server
      output: defaultbackend
      vendor: true

update:
  enabled: true
  github:
    identifier: kubernetes/ingress-gce
    use-tag: true
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - curl
  pipeline:
    - runs: |
        defaultbackend --help
    - runs: |
        defaultbackend > defaultbackend.log 2>&1 &

        sleep 5

        # Use a retry mechanism to check if the health endpoint is available
        for i in {1..5}; do
          if curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/healthz | grep -q "^200$"; then
            echo "Server is up"
            break
          else
            echo "Server not ready, retrying..."
            sleep 2
          fi
        done
    - name: Test 404 Response
      runs: |
        defaultbackend > defaultbackend.log 2>&1 &

        sleep 5

        for i in {1..5}; do
          if curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/ | grep -q "^404$"; then
            echo "Server 404ed"
            break
          else
            echo "Server not ready, retrying..."
            sleep 2
          fi
        done
