package:
  name: kubernetes-ingress-defaultbackend
  version: "1.34.2"
  epoch: 0
  description: 'A simple web server that respond 404 common used in kubernetes ingress, serve pages 404 at root and 200 at /healthz'
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes/ingress-gce
      tag: v${{package.version}}
      expected-commit: 6359d68f7f0bc3f0729bd6b44b6bc82652c2b640

  - uses: go/build
    with:
      packages: ./cmd/404-server
      output: defaultbackend
      vendor: true

update:
  enabled: true
  github:
    identifier: kubernetes/ingress-gce
    use-tag: true
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - wget
        - wait-for-it
  pipeline:
    - name: help message
      runs: |
        defaultbackend --help
    - name: Basic functional test for endpoints
      runs: |
        defaultbackend &
        wait-for-it localhost:8080 -t 10
        wget -q --server-response http://localhost:8080/ -O /dev/null 2>&1 | grep "404 Not Found"

        wget -q --server-response http://localhost:8080/healthz -O /dev/null 2>&1 | grep "200 OK"
