package:
  name: newrelic-prometheus-configurator
  version: 1.17.3
  epoch: 0
  description: New Relic Prometheus Configurator
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/newrelic-prometheus-configurator
      tag: v${{package.version}}
      expected-commit: 4b7b871dd6f1db920c42a9fe1a0a7f3c38c07778

  - runs: |
      GOOS=$(go env GOOS)
      GOARCH=$(go env GOARCH)
      make GOOS=${GOOS} GOARCH=${GOARCH} build
      install -Dm755 ./bin/prometheus-configurator-${GOOS}-${GOARCH} "${{targets.destdir}}"/usr/bin/prometheus-configurator

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/newrelic-prometheus-configurator
    strip-prefix: v
    use-tag: true
    tag-filter: v
