package:
  name: newrelic-prometheus-configurator
  version: "2.0.0"
  epoch: 1
  description: New Relic Prometheus Configurator
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/newrelic-prometheus-configurator
      tag: v${{package.version}}
      expected-commit: 66b59b3919d50f029f2b5f30fde8d5edb2dc8b77

  - uses: go/build
    with:
      packages: ./cmd/configurator
      output: prometheus-configurator
      ldflags: |
        -X main.integrationVersion="${{package.version}}"
        -X main.gitCommit="$(git rev-parse HEAD)"
        -X main.buildDate="$(date -d@$SOURCE_DATE_EPOCH +%Y%m%d-%H:%M:%S)"

update:
  enabled: true
  github:
    identifier: newrelic/newrelic-prometheus-configurator
    strip-prefix: v
    use-tag: true
    tag-filter: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        prometheus-configurator --help
