package:
  name: newrelic-prometheus-configurator
  version: 1.5.0
  epoch: 0
  description: New Relic Prometheus Configurator
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - go
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/newrelic-prometheus-configurator
      tag: v${{package.version}}
      expected-commit: c9d3e4faf3722054ffd1877bb992d9d8c562a41c

  - runs: |
      GOOS=$(go env GOOS)
      GOARCH=$(go env GOARCH)
      make GOOS=${GOOS} GOARCH=${GOARCH} build
      install -Dm755 ./bin/prometheus-configurator-${GOOS}-${GOARCH} "${{targets.destdir}}"/usr/bin/prometheus-configurator

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/newrelic-prometheus-configurator
    strip-prefix: v
    use-tag: true
    tag-filter: v
