package:
  name: nri-prometheus
  version: 2.21.0
  epoch: 4
  description: Fetch metrics in the Prometheus metrics inside or outside Kubernetes and send them to the New Relic Metrics platform.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-prometheus
      expected-commit: 224fe9e2756943703116a337b55609fd0d369b39
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0 golang.org/x/net@v0.23.0

  - uses: go/build
    with:
      packages: ./cmd/nri-prometheus
      output: nri-prometheus
      ldflags: -s -w

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/nri-prometheus
    strip-prefix: v
    tag-filter: v
