package:
  name: nri-prometheus
  version: 2.19.0
  epoch: 1
  description: Fetch metrics in the Prometheus metrics inside or outside Kubernetes and send them to the New Relic Metrics platform.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-prometheus
      expected-commit: a3d3f15292a9d5229fb3b1d0d5aebcd917d15ca6
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/nri-prometheus
      output: nri-prometheus
      ldflags: -s -w

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/nri-prometheus
    strip-prefix: v
    tag-filter: v
