package:
  name: nri-prometheus
  version: 2.19.0
  epoch: 0
  description: Fetch metrics in the Prometheus metrics inside or outside Kubernetes and send them to the New Relic Metrics platform.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-prometheus
      expected-commit: a3d3f15292a9d5229fb3b1d0d5aebcd917d15ca6
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/nri-prometheus
      output: nri-prometheus
      ldflags: -s -w
      # Mitigate CVE-2023-39325, CVE-2023-3978, CVE-2023-44487
      deps: google.golang.org/protobuf@v1.29.1 golang.org/x/net@v0.17.0

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/nri-prometheus
    strip-prefix: v
    tag-filter: v
