package:
  name: prometheus-podman-exporter
  version: 1.14.0
  epoch: 0
  description: Prometheus exporter for podman environments exposing containers, pods, images, volumes and networks information.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - btrfs-progs-dev
      - gpgme-dev
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/containers/prometheus-podman-exporter
      tag: v${{package.version}}
      expected-commit: 931c57834fc6216c886a0ecda3f37ecd142d4a7e

  - uses: go/bump
    with:
      deps: github.com/opencontainers/runc@v1.1.14

  - uses: go/build
    with:
      packages: .
      ldflags: |
        -X github.com/containers/prometheus-podman-exporter.cmd.buildVersion=${{package.version}}
        -X github.com/containers/prometheus-podman-exporter.cmd.buildRevision=$(cat VERSION  | grep REVISION | cut -d'=' -f2)
        -X github.com/containers/prometheus-podman-exporter.cmd.buildBranch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
      tags: remote,containers_image_openpgp
      output: podman_exporter

subpackages:
  - name: ${{package.name}}-compat
    description: "upstream image have executable placed at /bin"
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/bin/
          ln -sf /usr/bin/podman_exporter ${{targets.contextdir}}/bin/podman_exporter

update:
  enabled: true
  github:
    identifier: containers/prometheus-podman-exporter
    strip-prefix: v

test:
  pipeline:
    - runs: |
        podman_exporter --help
