package:
  name: prometheus-mongodb-exporter
  version: 0.40.0
  epoch: 2
  description: A Prometheus exporter for MongoDB including sharding, replication and storage engines
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/percona/mongodb_exporter
      expected-commit: cb3db8922fb068bba6ecd4c12c231cb63d970515
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      mv mongodb_exporter ${{targets.destdir}}/usr/bin/

  - uses: strip

subpackages:
  - name: prometheus-mongodb-exporter-bitnami-compat
    description: "compat package with bitnami/mongodb helm chart"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/bin
          ln -s /usr/bin/mongodb_exporter "${{targets.subpkgdir}}"/bin/mongodb_exporter

update:
  enabled: true
  github:
    identifier: percona/mongodb_exporter
    strip-prefix: v
