package:
  name: prometheus-mysqld-exporter
  # When bumping this version you can remove the `go get` line in the build script
  version: 0.15.1
  epoch: 2
  description: Prometheus Exporter for MySQL server metrics
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/mysqld_exporter
      tag: v${{package.version}}
      expected-commit: cc349684494b5038ec5a52233bdca9eb9291e6f2

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.17.0 golang.org/x/crypto@v0.17.0

  - runs: |
      make build

  - runs: |
      install -Dm755 mysqld_exporter "${{targets.destdir}}"/usr/bin/mysqld_exporter

  - uses: strip

update:
  enabled: true
  github:
    identifier: prometheus/mysqld_exporter
    strip-prefix: v
