package:
  name: prometheus-redis-exporter
  version: 1.59.0
  epoch: 1
  description: Prometheus Exporter for Redis Metrics.
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/oliver006/redis_exporter
      tag: v${{package.version}}
      expected-commit: 46861baae8aa1473d8cf2069d643058f072ec77a

  - uses: go/build
    with:
      packages: .
      output: redis_exporter
      ldflags: -s -w -extldflags -static -X main.BuildVersion=v${{package.version}} -X main.BuildCommitSha=$(git rev-parse HEAD) -X main.BuildDate=$(date +%F-%T)

  - uses: strip

update:
  enabled: true
  github:
    identifier: oliver006/redis_exporter
    strip-prefix: v
    tag-filter: v
