package:
  name: prometheus
  # When updating this version, please check if the go deps version pinning below
  # and remove if possible.
  version: 2.48.1
  epoch: 1
  description: The Prometheus monitoring system and time series database.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - go
      - nodejs

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/prometheus
      tag: v${{package.version}}
      expected-commit: 63894216648f0d6be310c9d16fb48293c45c9310

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0

  - runs: |
      GOLDFLAGS="-s -w -X github.com/prometheus/common/version.Version=${{package.version}}
        -X github.com/prometheus/common/version.Revision=WolfiLinux
        -X github.com/prometheus/common/version.Branch=master
        -X github.com/prometheus/common/version.BuildUser=$USER@$HOSTNAME
        -X github.com/prometheus/common/version.BuildDate=$(date -u "+%Y%m%d-%H:%M:%S" ${SOURCE_DATE_EPOCH:+-d @$SOURCE_DATE_EPOCH})
      "
      if [ -n "$LDFLAGS" ]; then
        # LDFLAGS (and only LDFLAGS) should be passed to -extldflags.
        GOLDFLAGS="$GOLDFLAGS -extldflags '$LDFLAGS'"
      fi

      # set -j1 to run things in the correct order in makefile
      # actual go building is still parallel
      make -j1 assets-compress

      go build \
        -trimpath \
        -mod=readonly \
        -ldflags "$GOLDFLAGS" \
        -tags netgo,builtinassets \
        ./cmd/prometheus
      go build \
        -trimpath \
        -mod=readonly \
        -ldflags "$GOLDFLAGS" \
        ./cmd/promtool

  - runs: |
      install -Dm755 prometheus "${{targets.destdir}}"/usr/bin/prometheus
      install -Dm755 promtool "${{targets.destdir}}"/usr/bin/promtool

      install -Dm644 prometheus.confd \
        "${{targets.destdir}}"/etc/conf.d/prometheus

      install -dm644 "${{targets.destdir}}"/var/lib/prometheus/data

      install -Dm644 -t "${{targets.destdir}}"/etc/prometheus \
        documentation/examples/prometheus.yml

      mkdir -p "${{targets.destdir}}"/etc/prometheus/console_libraries
      for file in console_libraries/*
      do
        install -Dm644 -t "${{targets.destdir}}"/etc/prometheus/console_libraries/ "$file"
      done

      mkdir -p "${{targets.destdir}}"/etc/prometheus/consoles
      for file in consoles/*
      do
        install -Dm644 -t "${{targets.destdir}}"/etc/prometheus/consoles/ "$file"
      done

  - uses: strip

subpackages:
  - name: ${{package.name}}-bitnami-compat
    description: "compat package with bitnami/prometheus image"
    pipeline:
      - uses: bitnami/compat
        with:
          image: prometheus
          version-path: 2/debian-11
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/opt/bitnami/prometheus/bin/
          mkdir -p ${{targets.subpkgdir}}/opt/bitnami/prometheus/conf

          chmod g+rwX ${{targets.subpkgdir}}/opt/bitnami

          cp ${{targets.destdir}}/usr/bin/prometheus ${{targets.subpkgdir}}/opt/bitnami/prometheus/bin/prometheus
          cp ${{targets.destdir}}/usr/bin/promtool ${{targets.subpkgdir}}/opt/bitnami/prometheus/bin/promtool
          cp -r ${{targets.destdir}}/etc/prometheus/* ${{targets.subpkgdir}}/opt/bitnami/prometheus/conf/
          cp -r ${{targets.destdir}}/var/lib/prometheus/data ${{targets.subpkgdir}}/opt/bitnami/prometheus/data

update:
  ignore-regex-patterns:
    - '\+stringlabels' # looks like stringlabels are still experimental, let's stick to the main version stream.
  enabled: true
  github:
    identifier: prometheus/prometheus
    strip-prefix: v
