package:
  name: prometheus-nats-exporter
  version: 0.14.0
  epoch: 0
  description: A Prometheus exporter for NATS metrics
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - go
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/nats-io/prometheus-nats-exporter
      tag: v${{package.version}}
      expected-commit: e3309761df3caf5e55dc876f200df6e8814c0d66

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      install -Dm755 prometheus-nats-exporter ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: nats-io/prometheus-nats-exporter
    strip-prefix: v
    use-tag: true
    tag-filter: v
