package:
  name: prometheus-elasticsearch-exporter
  version: 1.7.0
  epoch: 0
  description: Elasticsearch stats exporter for Prometheus
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus-community/elasticsearch_exporter
      tag: v${{package.version}}
      expected-commit: d24c8349fe86bab416e614c838175fb31fcd1063

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.17.0 golang.org/x/crypto@v0.17.0

  - runs: |
      make common-build

  - runs: |
      install -Dm755 elasticsearch_exporter "${{targets.destdir}}"/usr/bin/elasticsearch_exporter

  - uses: strip

subpackages:
  - name: prometheus-elasticsearch-exporter-bitnami-compat
    description: "compat package with bitnami/elasticsearch-exporter image"
    pipeline:
      - uses: bitnami/compat
        with:
          image: elasticsearch-exporter
          version-path: 1/debian-11
      - runs: |
          mkdir -p ${{targets.contextdir}}/opt/bitnami/elasticsearch-exporter/bin
          ln -s /usr/bin/elasticsearch_exporter ${{targets.contextdir}}/opt/bitnami/elasticsearch-exporter/bin/elasticsearch_exporter

update:
  enabled: true
  github:
    identifier: prometheus-community/elasticsearch_exporter
    strip-prefix: v
    use-tag: true
