package:
  name: prometheus-node-exporter
  version: 1.8.0
  epoch: 0
  description: Prometheus Exporter for machine metrics
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/node_exporter
      tag: v${{package.version}}
      expected-commit: cadb1d1190ad95c66b951758f01ff4c94e55e6ce

  - runs: |
      make build

  - runs: |
      install -Dm755 node_exporter "${{targets.destdir}}"/usr/bin/node_exporter

  - uses: strip

subpackages:
  - name: "prometheus-node-exporter-compat"
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          # The helm chart expects the node_exporter binaries to be in /bin instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"/bin
          ln -sf /usr/bin/node_exporter ${{targets.subpkgdir}}/bin/node_exporter
      - uses: strip

update:
  enabled: true
  github:
    identifier: prometheus/node_exporter
    strip-prefix: v
