package:
  name: prometheus-statsd-exporter
  version: 0.26.1
  epoch: 1
  description: StatsD exporter for Prometheus
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - curl
      - go
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/statsd_exporter
      expected-commit: 58769c7b4d128e7ceae1cf8d893260ed5b5afa4d
      tag: v${{package.version}}

  - runs: |
      make common-build

  - runs: |
      install -Dm755 statsd_exporter "${{targets.destdir}}"/usr/bin/statsd_exporter

  - uses: strip

update:
  enabled: true
  github:
    identifier: prometheus/statsd_exporter
    strip-prefix: v
