package:
  name: prometheus-elasticsearch-exporter
  version: 1.5.0
  epoch: 3
  description: Elasticsearch stats exporter for Prometheus
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - bash
      - build-base
      - go
      - curl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus-community/elasticsearch_exporter
      tag: v${{package.version}}
      expected-commit: ca4b2371710220ccc5ee0a87181d084c4a875033

  - runs: |
      go get golang.org/x/sys@v0.8.0
      go mod tidy
      make common-build

  - runs: |
      install -Dm755 elasticsearch_exporter "${{targets.destdir}}"/usr/bin/elasticsearch_exporter

  - uses: strip

update:
  enabled: true
  github:
    identifier: prometheus-community/elasticsearch_exporter
    strip-prefix: v
    use-tag: true
