package:
  name: prometheus-redis-exporter
  version: 1.67.0
  epoch: 0
  description: Prometheus Exporter for Redis Metrics.
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/oliver006/redis_exporter
      tag: v${{package.version}}
      expected-commit: e2bb7fd6af3b950efa3267e4b932531098dc06b0

  - uses: go/build
    with:
      packages: .
      output: redis_exporter
      ldflags: -s -w -extldflags -static -X main.BuildVersion=v${{package.version}} -X main.BuildCommitSha=$(git rev-parse HEAD) -X main.BuildDate=$(date +%F-%T)

  - uses: strip

subpackages:
  - name: ${{package.name}}-bitnami-compat
    pipeline:
      - uses: bitnami/compat
        with:
          image: redis-exporter
          version-path: 1/debian-12
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/opt/bitnami/redis-exporter/bin
          ln -s /usr/bin/redis_exporter ${{targets.subpkgdir}}/opt/bitnami/redis-exporter/bin/redis_exporter

update:
  enabled: true
  github:
    identifier: oliver006/redis_exporter
    strip-prefix: v
    tag-filter: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        redis_exporter --version
        redis_exporter --help
