package:
  name: prometheus-pushgateway
  version: 1.6.2
  epoch: 6
  description: Push acceptor for ephemeral and batch jobs.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - bash
      - build-base
      - go
      - curl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/pushgateway
      tag: v${{package.version}}
      expected-commit: dd0ca68e2cf68ba061ed9e73b19e1928a4f6338f

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.17.0

  - runs: |
      # Handle CVE-2023-39325 and CVE-2023-3978
      go mod tidy

      make build

  - runs: |
      install -Dm755 pushgateway "${{targets.destdir}}"/usr/bin/pushgateway

  - uses: strip

subpackages:
  - name: prometheus-pushgateway-bitnami-compat
    dependencies:
      provides:
        - prometheus-pushgateway-bitnami-compat=${{package.full-version}}
      runtime:
        # Required by startup scripts
        - busybox
        - bash
    pipeline:
      - uses: bitnami/compat
        with:
          image: pushgateway
          version-path: 1/debian-11
      - runs: |
          mkdir -p  ${{targets.subpkgdir}}/opt/bitnami/pushgateway/bin/
          chmod g+rwX ${{targets.subpkgdir}}/opt/bitnami
          ln -sf /usr/bin/pushgateway ${{targets.subpkgdir}}/opt/bitnami/pushgateway/bin/pushgateway

update:
  enabled: true
  github:
    identifier: prometheus/pushgateway
    strip-prefix: v
