package:
  name: prometheus-mysqld-exporter
  # When bumping this version you can remove the `go get` line in the build script
  version: 0.14.0
  epoch: 5
  description: Prometheus Exporter for MySQL server metrics
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - bash
      - build-base
      - go
      - curl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/mysqld_exporter
      tag: v${{package.version}}
      expected-commit: ca1b9af82a471c849c529eb8aadb1aac73e7b68c

  - runs: |
      # Mitigate GHSA-vvpx-j8f3-3w6h
      go get golang.org/x/net@v0.7.0

      # Mitigate GHSA-gwc9-m7rh-j2ww and GHSA-8c26-wmh5-6g9v
      go get golang.org/x/crypto@v0.7.0

      # Mitigate GHSA-7rg2-cxvp-9p7p
      go get github.com/prometheus/exporter-toolkit@v0.7.3
      go mod tidy
      make build

  - runs: |
      install -Dm755 mysqld_exporter "${{targets.destdir}}"/usr/bin/mysqld_exporter

  - uses: strip

update:
  enabled: true
  github:
    identifier: prometheus/mysqld_exporter
    strip-prefix: v
