package:
  name: prometheus-adapter
  version: 0.11.2
  epoch: 2
  description: Prometheus Adapter for Kubernetes Metrics APIs
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - go
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/prometheus-adapter
      expected-commit: ed03656b3bbece403ebc8fcddc40513039089931
      tag: v${{package.version}}

  - runs: |
      # Handle CVE-2023-39325 and CVE-2023-3978
      go get golang.org/x/net@v0.17.0

      # Mitigate CVE-2023-47108
      go get go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.0
      go get go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.46.0
      go get go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc@v1.21.0
      go get go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp@v1.21.0
      go mod tidy

      make prometheus-adapter

  - runs: |
      install -Dm755 adapter "${{targets.destdir}}"/usr/bin/adapter

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/prometheus-adapter
    strip-prefix: v
