package:
  name: prometheus-mysqld-exporter
  # When bumping this version you can remove the `go get` line in the build script
  version: 0.16.0
  epoch: 1
  description: Prometheus Exporter for MySQL server metrics
  copyright:
    - license: Apache-2.0
    - license: LicenseRef-NOTICE
      license-path: NOTICE

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/mysqld_exporter
      tag: v${{package.version}}
      expected-commit: c366424252a3140838a344a6cb0d40d44f1be91d

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0

  - uses: go/build
    with:
      packages: .
      output: mysqld_exporter

subpackages:
  - name: prometheus-mysqld-exporter-bitnami-compat
    description: "compat package with bitnami/mysqld-exporter image"
    pipeline:
      - uses: bitnami/compat
        with:
          image: mysqld-exporter
          version-path: 0/debian-12
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/opt/bitnami/mysqld-exporter/bin/
          chmod g+rwX ${{targets.subpkgdir}}/opt/bitnami
          ln -sf /usr/bin/mysqld_exporter ${{targets.subpkgdir}}/opt/bitnami/mysqld-exporter/bin/mysqld_exporter
          mkdir -p ${{targets.subpkgdir}}/bin
          ln -sf /usr/bin/mysqld_exporter ${{targets.subpkgdir}}/bin/mysqld_exporter
    test:
      pipeline:
        - runs: |
            run-script --version
            run-script --help

update:
  enabled: true
  github:
    identifier: prometheus/mysqld_exporter
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        mysqld_exporter --version
        mysqld_exporter --help
