package:
  name: prometheus-pushgateway
  version: 1.7.0
  epoch: 0
  description: Push acceptor for ephemeral and batch jobs.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/pushgateway
      tag: v${{package.version}}
      expected-commit: 109280c17d29059623c6f5dbf1d6babab34166cf

  - runs: |
      make build

  - runs: |
      install -Dm755 pushgateway "${{targets.destdir}}"/usr/bin/pushgateway

  - uses: strip

subpackages:
  - name: prometheus-pushgateway-bitnami-compat
    dependencies:
      runtime:
        # Required by startup scripts
        - busybox
        - bash
    pipeline:
      - uses: bitnami/compat
        with:
          image: pushgateway
          version-path: 1/debian-11
      - runs: |
          mkdir -p  ${{targets.subpkgdir}}/opt/bitnami/pushgateway/bin/
          chmod g+rwX ${{targets.subpkgdir}}/opt/bitnami
          ln -sf /usr/bin/pushgateway ${{targets.subpkgdir}}/opt/bitnami/pushgateway/bin/pushgateway

update:
  enabled: true
  github:
    identifier: prometheus/pushgateway
    strip-prefix: v
