package:
  name: prometheus-stackdriver-exporter
  version: 0.13.0
  epoch: 1
  description: Google Stackdriver Prometheus exporter
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - bash
      - build-base
      - go
      - curl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus-community/stackdriver_exporter
      tag: v${{package.version}}
      expected-commit: ba71119bfcb23bfa149d509213a930245e340fc5

  - runs: |
      # Mitigate GHSA-vvpx-j8f3-3w6h
      go get golang.org/x/net@v0.7.0
      go mod tidy
      make common-build

  - runs: |
      install -Dm755 stackdriver_exporter "${{targets.destdir}}"/usr/bin/stackdriver_exporter

  - uses: strip

update:
  enabled: true
  github:
    identifier: prometheus-community/stackdriver_exporter
    strip-prefix: v
    use-tag: true

advisories:
  CVE-2022-41723:
    - timestamp: 2023-05-02T22:52:07.740978573Z
      status: fixed
      fixed-version: 0.13.0-r0

secfixes:
  0.13.0-r0:
    - CVE-2022-41723
