package:
  name: prometheus-mysqld-exporter
  # When bumping this version you can remove the `go get` line in the build script
  version: 0.15.0
  epoch: 7
  description: Prometheus Exporter for MySQL server metrics
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/mysqld_exporter
      tag: v${{package.version}}
      expected-commit: 6ca2a42f97f3403c7788ff4f374430aa267a6b6b

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.17.0

  - runs: |
      make build

  - runs: |
      install -Dm755 mysqld_exporter "${{targets.destdir}}"/usr/bin/mysqld_exporter

  - uses: strip

update:
  enabled: true
  github:
    identifier: prometheus/mysqld_exporter
    strip-prefix: v
