package:
  name: prometheus-stackdriver-exporter
  version: 0.14.1
  epoch: 7
  description: Google Stackdriver Prometheus exporter
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus-community/stackdriver_exporter
      tag: v${{package.version}}
      expected-commit: 3e21ec35b0af84efd3a4c0e1af120bc22a5ffbc8

  - runs: |
      make common-build

  - runs: |
      install -Dm755 stackdriver_exporter "${{targets.destdir}}"/usr/bin/stackdriver_exporter

  - uses: strip

update:
  enabled: true
  github:
    identifier: prometheus-community/stackdriver_exporter
    strip-prefix: v
    use-tag: true
