package:
  name: prometheus-postgres-exporter
  version: 0.13.1
  epoch: 1
  description: Prometheus Exporter for Postgres server metrics
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - bash
      - build-base
      - go
      - curl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus-community/postgres_exporter
      tag: v${{package.version}}
      expected-commit: bf4e4fb6cca3191d3c41df2efdf5d15d17b5fa60

  - runs: |
      go mod tidy
      make build

  - runs: |
      install -Dm755 postgres_exporter "${{targets.destdir}}"/usr/bin/postgres_exporter

  - uses: strip

update:
  enabled: true
  github:
    identifier: prometheus-community/postgres_exporter
    strip-prefix: v
