package:
  name: prometheus-stackdriver-exporter
  version: 0.14.0
  epoch: 0
  description: Google Stackdriver Prometheus exporter
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - bash
      - build-base
      - go
      - curl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus-community/stackdriver_exporter
      tag: v${{package.version}}
      expected-commit: 6cb7206e17edca8fb4a95258a25875eafe9b38bd

  - runs: |
      # Mitigate GHSA-vvpx-j8f3-3w6h
      go get golang.org/x/net@v0.7.0
      go mod tidy
      make common-build

  - runs: |
      install -Dm755 stackdriver_exporter "${{targets.destdir}}"/usr/bin/stackdriver_exporter

  - uses: strip

update:
  enabled: true
  github:
    identifier: prometheus-community/stackdriver_exporter
    strip-prefix: v
    use-tag: true
