package:
  name: prometheus-blackbox-exporter
  version: 0.24.0
  epoch: 3
  description: Blackbox prober exporter
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - go
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/blackbox_exporter
      tag: v${{package.version}}
      expected-commit: 0b0467473916fd9e8526e2635c2a0b1c56011dff

  - runs: |
      make common-build

  - runs: |
      install -Dm755 blackbox_exporter "${{targets.destdir}}"/usr/bin/blackbox_exporter

  - uses: strip

update:
  enabled: true
  github:
    identifier: prometheus/blackbox_exporter
    strip-prefix: v
    use-tag: true
    tag-filter: v
