package:
  name: prometheus-adapter
  version: 0.12.0
  epoch: 5
  description: Prometheus Adapter for Kubernetes Metrics APIs
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - go
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/prometheus-adapter
      expected-commit: 17cef511b1854441490bceeca7a710a04ce091ad
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.31.0 golang.org/x/net@v0.33.0

  - runs: |
      make prometheus-adapter

  - runs: |
      install -Dm755 adapter "${{targets.destdir}}"/usr/bin/adapter

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/prometheus-adapter
    strip-prefix: v
