package:
  name: prometheus-bind-exporter
  version: 0.7.0
  epoch: 5
  description: Prometheus exporter for BIND
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - go
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus-community/bind_exporter
      tag: v${{package.version}}
      expected-commit: b9e01efa3fa37e78c65b2f09e84e027a954b5d32

  - runs: |
      make common-build
      mkdir -p ${{targets.destdir}}/usr/bin
      cp bind_exporter ${{targets.destdir}}/usr/bin/

update:
  enabled: true
  github:
    identifier: prometheus-community/bind_exporter
    strip-prefix: v
    use-tag: true
    tag-filter: v
