package:
  name: prometheus-adapter
  version: 0.11.2
  epoch: 3
  description: Prometheus Adapter for Kubernetes Metrics APIs
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - go
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/prometheus-adapter
      expected-commit: ed03656b3bbece403ebc8fcddc40513039089931
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.17.0 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.0 go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.46.0 go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc@v1.21.0 golang.org/x/crypto@v0.17.0

  - runs: |
      make prometheus-adapter

  - runs: |
      install -Dm755 adapter "${{targets.destdir}}"/usr/bin/adapter

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/prometheus-adapter
    strip-prefix: v
