package:
  name: prometheus
  version: 2.44.0
  epoch: 1
  description: The Prometheus monitoring system and time series database.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - bash
      - go
      - nodejs

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/prometheus/prometheus/archive/v${{package.version}}.tar.gz
      expected-sha256: cbaaa0e17a355abc4a90d4ead952620aa1bca8fad4a95fd81ac68c0d963add26

  - runs: |
      # Mitigate GHSA-232p-vwff-86mp
      # Mitigate GHSA-33pg-m6jh-5237
      # Mitigate GHSA-6wrf-mxfj-pf5p
      go get github.com/docker/docker@v23.0.3+incompatible

      # Mitigate GHSA-hw7c-3rfg-p46j
      go get google.golang.org/protobuf@v1.29.1

  - runs: |
      GOLDFLAGS="-s -w -X github.com/prometheus/common/version.Version=${{package.version}}
        -X github.com/prometheus/common/version.Revision=WolfiLinux
        -X github.com/prometheus/common/version.Branch=master
        -X github.com/prometheus/common/version.BuildUser=$USER@$HOSTNAME
        -X github.com/prometheus/common/version.BuildDate=$(date -u "+%Y%m%d-%H:%M:%S" ${SOURCE_DATE_EPOCH:+-d @$SOURCE_DATE_EPOCH})
      "
      if [ -n "$LDFLAGS" ]; then
        # LDFLAGS (and only LDFLAGS) should be passed to -extldflags.
        GOLDFLAGS="$GOLDFLAGS -extldflags '$LDFLAGS'"
      fi

      # set -j1 to run things in the correct order in makefile
      # actual go building is still parallel
      make -j1 assets-compress

      go build \
        -trimpath \
        -mod=readonly \
        -ldflags "$GOLDFLAGS" \
        -tags netgo,builtinassets \
        ./cmd/prometheus
      go build \
        -trimpath \
        -mod=readonly \
        -ldflags "$GOLDFLAGS" \
        ./cmd/promtool

  - runs: |
      install -Dm755 prometheus "${{targets.destdir}}"/usr/bin/prometheus
      install -Dm755 promtool "${{targets.destdir}}"/usr/bin/promtool

      install -Dm644 prometheus.confd \
        "${{targets.destdir}}"/etc/conf.d/prometheus

      install -dm644 "${{targets.destdir}}"/var/lib/prometheus/data

      install -Dm644 -t "${{targets.destdir}}"/etc/prometheus \
        documentation/examples/prometheus.yml

      mkdir -p "${{targets.destdir}}"/etc/prometheus/console_libraries
      for file in console_libraries/*
      do
        install -Dm644 -t "${{targets.destdir}}"/etc/prometheus/console_libraries/ "$file"
      done

      mkdir -p "${{targets.destdir}}"/etc/prometheus/consoles
      for file in consoles/*
      do
        install -Dm644 -t "${{targets.destdir}}"/etc/prometheus/consoles/ "$file"
      done

  - uses: strip

update:
  ignore-regex-patterns:
    - '\+stringlabels' # looks like stringlabels are still experimental, let's stick to the main version stream.
  enabled: true
  github:
    identifier: prometheus/prometheus
    strip-prefix: v
