package:
  name: prometheus-beat-exporter
  version: 0.4.0
  epoch: 7
  description: Elastic beat-exporter for Prometheus
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/trustpilot/beat-exporter
      tag: ${{package.version}}
      expected-commit: 82cf1b275f77c317789852a985243409d0996ceb

  # CVE-2022-29526 and CVE-2023-44487
  - uses: go/bump
    with:
      deps: golang.org/x/sys@v0.13.0 github.com/prometheus/client_golang@v1.11 google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      modroot: .
      packages: .
      output: beat-exporter
      ldflags: -w -X github.com/prometheus/common/version.Version=${{package.version}} -X github.com/prometheus/common/version.Revision=$(git rev-parse HEAD) -X github.com/prometheus/common/version.BuildDate=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")
      tags: netgo,static_build

  - uses: strip

update:
  enabled: true
  github:
    identifier: trustpilot/beat-exporter

test:
  pipeline:
    - runs: |
        beat-exporter --version
        beat-exporter --help
