package:
  name: prometheus-node-exporter
  # When bumping this version you can remove the `go get` line in the build script
  version: 1.5.0
  epoch: 2
  description: Prometheus Exporter for machine metrics
  copyright:
    - license: Apache-2.0
environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - bash
      - build-base
      - go
      - curl
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/node_exporter
      tag: v${{package.version}}
      expected-commit: 1b48970ffcf5630534fb00bb0687d73c66d1c959
  - runs: |
      # Mitigate GHSA-vvpx-j8f3-3w6h
      go get golang.org/x/net@v0.7.0
      go mod tidy
      make build
  - runs: |
      install -Dm755 node_exporter "${{targets.destdir}}"/usr/bin/node_exporter
  - uses: strip
update:
  enabled: true
  github:
    identifier: prometheus/node_exporter
    strip-prefix: v