package:
  name: py3-iniconfig
  version: 2.0.0
  epoch: 2
  description: brain-dead simple parsing of ini files
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - ca-certificates-bundle
      - py3-pip
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pytest-dev/iniconfig
      expected-commit: 93f5930e668c0d1ddf4597e38dd0dea4e2665e7a
      tag: v${{package.version}}

  - name: Python build
    runs: |
      pip install . --prefix=/usr --root=${{targets.destdir}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: pytest-dev/iniconfig
    tag-filter: v
    strip-prefix: v
