package:
  name: swagger
  version: "0.33.1"
  epoch: 3 # GHSA-j5w8-q4qc-rx2x
  description: Swagger 2.0 implementation for go
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/go-swagger/go-swagger
      tag: v${{package.version}}
      expected-commit: 2af7725271cf99ace5d44ab134acb53bffcc5734

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/crypto@v0.45.0

  - uses: go/build
    with:
      packages: ./cmd/swagger
      output: swagger

  - uses: strip

update:
  enabled: true
  github:
    identifier: go-swagger/go-swagger
    strip-prefix: v

test:
  pipeline:
    - runs: |
        swagger version
