package:
  name: traefik
  version: 2.10.1
  epoch: 5
  description: The Cloud Native Application Proxy
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - go
      - build-base
      - ca-certificates-bundle
      - git

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/traefik/traefik/releases/download/v${{package.version}}/traefik-v${{package.version}}.src.tar.gz
      expected-sha256: 34c19da8a28e10e5634afd7336a9b7944dbf21bfbacf4248d0140c329ef0049f

  - runs: |
      go get go.mongodb.org/mongo-driver@v1.11.2
      go get github.com/Azure/go-autorest/autorest/adal@v0.9.22
      go get github.com/hashicorp/go-discover@v0.0.0-20230125175744-70b45b3eb8b7
      go get github.com/hashicorp/consul@v1.15.0
      go get github.com/docker/docker@v20.10.24
      go get github.com/docker/distribution@v2.8.2-beta.1
      go get github.com/hashicorp/consul@v1.15.3
      go mod tidy
      VERSION=v${{package.version}} ./script/make.sh generate binary
      mkdir -p "${{targets.destdir}}/usr/bin"
      mv ./dist/traefik "${{targets.destdir}}"/usr/bin
      go version -m "${{targets.destdir}}"/usr/bin/traefik

update:
  enabled: true
  github:
    identifier: traefik/traefik
    strip-prefix: v
