package:
  name: traefik
  version: 3.0.0
  epoch: 2
  description: The Cloud Native Application Proxy
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: d99d2f95e66a28ee8180634dc80fdf13ba68c62a
      repository: https://github.com/traefik/traefik
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/traefik/traefik/v3@v3.0.0-beta5
      modroot: .

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd/traefik
      output: traefik
      ldflags: |
        -X github.com/traefik/traefik/v3/pkg/version.Version=${{package.version}}
        -X github.com/traefik/traefik/v3/pkg/version.BuildDate=$(date -u '+%Y-%m-%d_%I:%M:%S%p')
        -X github.com/traefik/traefik/v3/pkg/version.Codename=$CODENAME

update:
  enabled: true
  github:
    identifier: traefik/traefik
    strip-prefix: v

test:
  pipeline:
    - runs: |
        set -o pipefail
        traefik version | grep ${{package.version}}
