package:
  name: traefik
  version: 2.11.0
  epoch: 0
  description: The Cloud Native Application Proxy
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0c8778639a3cade0cf73aa26f56f822a4fb835e8
      repository: https://github.com/traefik/traefik
      tag: v${{package.version}}

  - runs: |
      mkdir -p "${{targets.destdir}}/usr/bin"
      VERSION=v${{package.version}}
      GOOS=$(go env GOOS) GOARCH=$(go env GOARCH)
      DATE=$(date -u '+%Y-%m-%d_%I:%M:%S%p')
      CGO_ENABLED=0 GOGC=off GOOS=${GOOS} GOARCH=${GOARCH} go build  -ldflags "-s -w \
      -X github.com/traefik/traefik/v3/pkg/version.Version=$(VERSION) \
      -X github.com/traefik/traefik/v3/pkg/version.Codename=$(CODENAME) \
      -X github.com/traefik/traefik/v3/pkg/version.BuildDate=$(DATE)" \
      -installsuffix nocgo -o "${{targets.destdir}}"/usr/bin/ ./cmd/traefik
      go version -m "${{targets.destdir}}"/usr/bin/traefik

update:
  enabled: true
  github:
    identifier: traefik/traefik
    strip-prefix: v
