package:
  name: traefik-3.6
  version: "3.6.0"
  epoch: 0 # GHSA-47m2-4cr7-mhcw
  description: The Cloud Native Application Proxy
  copyright:
    - license: MIT
  dependencies:
    provides:
      - traefik=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go
      - nodejs-20
      - yarn-berry

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 06db5168c0d936a0716cbede56bc2cd332be0d4f
      repository: https://github.com/traefik/traefik
      tag: v${{package.version}}

  - working-directory: webui
    runs: |
      yarn install
      yarn build

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd/traefik
      output: traefik
      ldflags: |
        -X github.com/traefik/traefik/v3/pkg/version.Version=${{package.version}}
        -X github.com/traefik/traefik/v3/pkg/version.BuildDate=$(date -u -d "@$SOURCE_DATE_EPOCH" '+%Y-%m-%d_%I:%M:%S%p')
        -X github.com/traefik/traefik/v3/pkg/version.Codename=$CODENAME

update:
  enabled: true
  github:
    identifier: traefik/traefik
    strip-prefix: v
    tag-filter: v3.6.

test:
  pipeline:
    - runs: |
        set -o pipefail
        traefik version | grep ${{package.version}}
        traefik --help
    - name: Run and test traefik
      uses: test/daemon-check-output
      with:
        start: traefik --ping=true --ping.entryPoint=traefik --api.insecure=true --log.level=DEBUG
        timeout: 30
        expected_output: |
          Creating middleware
          Setting up redirection
