package:
  name: traefik
  version: 2.9.9
  epoch: 1
  description: The Cloud Native Application Proxy
  copyright:
    - license: MIT

secfixes:
  2.9.6-r0:
    - CVE-2022-23469
    - CVE-2022-46153
  2.9.8-r1:
    - CVE-2021-41803
    - CVE-2022-40716

environment:
  contents:
    packages:
      - busybox
      - go
      - build-base
      - ca-certificates-bundle
      - git

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/traefik/traefik/releases/download/v${{package.version}}/traefik-v${{package.version}}.src.tar.gz
      expected-sha256: 3f0587ade4aae67c8e52ee3d499e0e908d50e4c9751d9850f02054fb7c352c45
  - runs: |
      go get go.mongodb.org/mongo-driver@v1.11.2
      go get github.com/Azure/go-autorest/autorest/adal@v0.9.22
      go get github.com/hashicorp/go-discover@v0.0.0-20230125175744-70b45b3eb8b7
      go get github.com/hashicorp/consul@v1.15.0
      go mod tidy
      cat go.mod
      VERSION=v${{package.version}} ./script/make.sh generate binary
      mkdir -p "${{targets.destdir}}/usr/bin"
      mv ./dist/traefik "${{targets.destdir}}"/usr/bin
      go version -m "${{targets.destdir}}"/usr/bin/traefik

advisories:
  CVE-2021-41803:
    - timestamp: 2023-03-07T11:51:57.26224-05:00
      status: fixed
      fixed-version: 2.9.8-r1
  CVE-2022-23469:
    - timestamp: 2023-01-29T11:56:03.991319-05:00
      status: fixed
      fixed-version: 2.9.6-r0
  CVE-2022-40716:
    - timestamp: 2023-03-07T11:52:26.180256-05:00
      status: fixed
      fixed-version: 2.9.8-r1
  CVE-2022-46153:
    - timestamp: 2023-01-29T11:56:03.989795-05:00
      status: fixed
      fixed-version: 2.9.6-r0

update:
  enabled: true
  github:
    identifier: traefik/traefik
    strip-prefix: v
