package:
  name: traefik
  version: 2.10.4
  epoch: 0
  description: The Cloud Native Application Proxy
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - go
      - build-base
      - ca-certificates-bundle
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/traefik/traefik
      expected-commit: 0bd367ebbdcd6eb7e203549f799c7345320cd58f
      tag: v${{package.version}}

  - runs: |
      go mod edit -replace github.com/hashicorp/consul=github.com/hashicorp/consul@v1.14.7
      go get github.com/docker/distribution@v2.8.2
      go get github.com/docker/docker@v20.10.24
      go mod tidy
      VERSION=v${{package.version}} ./script/make.sh generate binary
      mkdir -p "${{targets.destdir}}/usr/bin"
      mv ./dist/traefik "${{targets.destdir}}"/usr/bin
      go version -m "${{targets.destdir}}"/usr/bin/traefik

update:
  enabled: true
  github:
    identifier: traefik/traefik
    strip-prefix: v
