name: CI build action

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Build changed OS packages (CI)
    runs-on: ubuntu-16-core

    permissions:
      packages: write
      contents: read

    steps:
      - name: Generate snapshot date
        id: snapshot-date
        run: |
          echo "date=$(date -u +%Y%m%d)" >> $GITHUB_OUTPUT
          echo "epoch=$(date -u +%s)" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/checkout@v3

      - uses: chainguard-dev/actions/setup-melange@main

      - uses: google-github-actions/setup-gcloud@v0

      - name: 'Generate local signing key'
        run: |
          make MELANGE="melange" local-melange.rsa

      - name: 'Sync public package repository'
        run: |
          mkdir "${{ github.workspace }}/packages"
          gsutil -m rsync -x "aarch64/.*" -r gs://wolfi-production-registry-destination/os/ "${{ github.workspace }}/packages/"
          find "${{ github.workspace }}/packages" -print -exec touch \{} \;

      - name: 'Build Wolfi'
        run: |
          make --debug MELANGE="sudo melange" MELANGE_DIR=/usr/share/melange MELANGE_EXTRA_OPTS="--keyring-append ${{ github.workspace }}/wolfi-signing.rsa.pub" REPO="${{ github.workspace }}/packages" -j1

      - name: Generate dependency svg
        id: svg
        uses: docker://ghcr.io/wolfi-dev/wolfictl:latest
        with:
          entrypoint: wolfictl
          args: svg

      - uses: actions/upload-artifact@v3
        with:
          name: dag.svg
          path: dag.svg
