name: Build Packages Production

on:
  push:
    branches: ['main']
    paths-ignore: ['README.md']
  workflow_dispatch:

jobs:
  build:
    name: Build OS packages
    runs-on: ubuntu-16-core
    if: github.repository == 'wolfi-dev/os'

    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
      - name: Generate snapshot date
        id: snapshot-date
        run: |
          echo "date=$(date -u +%Y%m%d)" >> $GITHUB_OUTPUT
          echo "epoch=$(date -u +%s)" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/checkout@v3
      - run: echo "${{ secrets.MELANGE_RSA }}" > ./wolfi-signing.rsa
      - run: |
          sudo mkdir -p /etc/apk/keys
          sudo cp ./wolfi-signing.rsa.pub /etc/apk/keys/wolfi-signing.rsa.pub

      - uses: chainguard-dev/actions/setup-melange@main

      - id: auth
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "projects/618116202522/locations/global/workloadIdentityPools/prod-shared-e350/providers/prod-shared-gha"
          service_account: "prod-images-ci@prod-images-c6e5.iam.gserviceaccount.com"

      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: prod-images-c6e5
          version: 399.0.0

      - name: 'Check that GCloud is properly configured'
        run: |
          gcloud info
          gcloud --quiet alpha storage ls

      - name: 'Prepare package repository'
        run: |
          mkdir -p "${{ github.workspace }}/packages"
          cp /etc/apk/keys/wolfi-signing.rsa.pub ${{ github.workspace }}/packages/wolfi-signing.rsa.pub

      - name: 'Sync public package repository'
        run: |
          mkdir -p "${{ github.workspace }}/packages"
          gsutil -m rsync -x "aarch64/.*" -r gs://wolfi-production-registry-destination/os/ "${{ github.workspace }}/packages/"
          find "${{ github.workspace }}/packages" -print -exec touch \{} \;

      - name: 'Build Wolfi'
        run: |
          make MELANGE="sudo melange" MELANGE_DIR=/usr/share/melange KEY=wolfi-signing.rsa REPO="${{ github.workspace }}/packages" -j1

      - name: 'Normalize repository permissions'
        run: |
          sudo chown -R $(id -u):$(id -g) "${{ github.workspace }}/packages"

      - name: 'Upload the repository to a bucket'
        run: |
          cp /etc/apk/keys/wolfi-signing.rsa.pub ${{ github.workspace }}/packages/wolfi-signing.rsa.pub
          gcloud --quiet storage cp \
              --recursive \
              --cache-control="public, max-age=0" \
              "${{ github.workspace }}/packages/*" gs://wolfi-production-registry-destination/os/

  postrun:
    name: Build (arm64)
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844 # v1.23.0
        id: slack
        with:
          payload: '{"text": "[push-production] failure: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
