name: Build security database Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build security database
    runs-on: ubuntu-latest
    if: github.repository == 'wolfi-dev/os'

    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3

      - id: auth
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "projects/618116202522/locations/global/workloadIdentityPools/prod-shared-e350/providers/prod-shared-gha"
          service_account: "prod-images-ci@prod-images-c6e5.iam.gserviceaccount.com"

      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: prod-images-c6e5

      - name: 'Check that GCloud is properly configured'
        run: |
          gcloud info
          gcloud --quiet alpha storage ls

      - name: 'Build wolfi-secdb'
        run: |
          git clone https://github.com/chainguard-dev/wolfi-secdb
          pushd wolfi-secdb
          go build
          popd

      - name: 'Generate security database'
        run: |
          ./wolfi-secdb/wolfi-secdb generate . --repo-name os

      - name: 'Upload the security database to a bucket'
        run: |
          # Don't cache the security.json.
          gcloud --quiet alpha storage cp \
              --cache-control=no-store \
              ${{ github.workspace }}/security.json \
              gs://wolfi-production-registry-destination/os/
